<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="MSI" failures="2" tests="2" name="Default test(failed)" time="0.083" errors="0" timestamp="2023-04-19T09:07:22 IST">
  <testcase classname="testngTestCases.FailedTestCases" name="tc3" time="0.02">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testngTestCases.FailedTestCases.tc3(FailedTestCases.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- tc3 -->
  <testcase classname="testngTestCases.FailedTestCases" name="tc1" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testngTestCases.FailedTestCases.tc1(FailedTestCases.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- tc1 -->
  <testcase classname="testngTestCases.FailedTestCases" name="tc2" time="0.0">
    <ignored/>
  </testcase> <!-- tc2 -->
</testsuite> <!-- Default test(failed) -->
